# Generated by Django 4.0.7 on 2022-12-14 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='details',
        ),
    ]
